import { IntelligenceDashboardTemplate } from "@/components/layout/intelligence-dashboard-template";
import { 
  Sparkles, LineChart, Battery, Plug, Wand2, Wrench, Lightbulb, Rocket, 
  Brain, Settings, ShieldAlert, Cpu, BarChart3, HelpCircle, HardDrive, RefreshCw, Sun 
} from "lucide-react";

const DATA_MAP: Record<string, {
  title: string;
  subtitle: string;
  categoryName: string;
  stats: Array<{
    label: string;
    value: string;
    change?: string;
    changeType?: "positive" | "negative" | "neutral";
  }>;
  widgets: Array<{
    title: string;
    description: string;
    content: React.ReactNode;
  }>;
}> = {
  assistant: {
    title: "AI Assistant Node",
    subtitle: "Ask EV-related questions, calculate specific range estimations, and receive intelligent advice from Nexiora's fine-tuned LLM.",
    categoryName: "AI Assistant",
    stats: [
      { label: "Queries Processed", value: "1.4M+ Requests", change: "+34% this wk", changeType: "positive" },
      { label: "Accuracy Index", value: "99.2%", change: "Validated answers", changeType: "positive" },
      { label: "Response Latency", value: "120ms Avg", change: "Ultra fast edge", changeType: "positive" },
      { label: "LLM Version", value: "NexioraGPT v2.4", change: "Fine-tuned model", changeType: "neutral" }
    ],
    widgets: [
      {
        title: "Conversational Diagnostics",
        description: "Type queries regarding EV ranges, charger compatibilities, or BMS error codes for instant advice.",
        content: (
          <div className="w-full space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Brain className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Ask anything:</p>
                <p className="text-xs text-muted-foreground/75">&quot;Explain LFP vs NMC cell chemistry lifespans under peak desert heat.&quot;</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Cpu className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Edge AI Processor</p>
                <p className="text-xs text-muted-foreground/75">Answers are generated by low-latency server models.</p>
              </div>
            </div>
          </div>
        )
      },
      {
        title: "Policy & Incentives Database",
        description: "Stays constantly updated on latest state-level tax write-offs and EV registration exemptions.",
        content: (
          <div className="w-full space-y-3 text-xs text-muted-foreground/80">
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Incentives Matcher:</span> Connects registered companies to PM E-Drive grants.
            </div>
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Compliance Checks:</span> Evaluates battery certificates against local regulations.
            </div>
          </div>
        )
      }
    ]
  },
  analytics: {
    title: "EV Analytics Engine",
    subtitle: "Explore detailed EV sales volumes, charging infrastructure density curves, battery mineral price shifts, and global adoption data.",
    categoryName: "EV Analytics",
    stats: [
      { label: "Data points Ingested", value: "450M Rows", change: "Real-time updates", changeType: "positive" },
      { label: "Trend Forecasting", value: "96.4% Accurate", change: "ML Regression", changeType: "positive" },
      { label: "Dashboard Widgets", value: "28 Nodes", change: "Interactive charts", changeType: "neutral" },
      { label: "Data Refresh Rate", value: "Every 5 Mins", change: "Automated cron", changeType: "positive" }
    ],
    widgets: [
      {
        title: "Highway Charger Utilization",
        description: "Visualizes grid utilization patterns across prime highway networks to spot under-served zones.",
        content: (
          <div className="w-full space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <LineChart className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Peak Load (4 PM - 8 PM)</p>
                <p className="text-xs text-muted-foreground/75">Suggests optimal dynamic pricing scales to shift chargers load.</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <BarChart3 className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Grid Stability Index</p>
                <p className="text-xs text-muted-foreground/75">Monitors utility voltage health under concurrent fast charges.</p>
              </div>
            </div>
          </div>
        )
      },
      {
        title: "Lithium Price Indexing",
        description: "Predictive commodity prices for battery chemistries like LFP and NMC raw minerals.",
        content: (
          <div className="w-full space-y-3 text-xs text-muted-foreground/80">
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Lithium Carbonate:</span> Predicted downward trend stabilizing pack supply costs.
            </div>
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Recyclable Minerals:</span> Market index shows hydrometallurgical cobalt up by 4%.
            </div>
          </div>
        )
      }
    ]
  },
  battery: {
    title: "Battery Intelligence Portal",
    subtitle: "Analyze lithium cell battery health decay rates, predict BMS failure conditions, and monitor state-of-health curves.",
    categoryName: "Battery Intel",
    stats: [
      { label: "Packs Monitored", value: "24,000+ Packs", change: "Active IoT feeds", changeType: "positive" },
      { label: "Thermal Anomalies", value: "0 Incidents", change: "100% Safe records", changeType: "positive" },
      { label: "BMS Sync Latency", value: "Real-time", change: "CAN Bus MQTT link", changeType: "neutral" },
      { label: "Avg Life Extension", value: "+2.5 Years", change: "Optimized charging", changeType: "positive" }
    ],
    widgets: [
      {
        title: "Predictive Capacity Retention",
        description: "Uses historical telemetry data to forecast battery capacity limits over a 10-year lifespan.",
        content: (
          <div className="w-full space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Battery className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Internal Impedance Tracking</p>
                <p className="text-xs text-muted-foreground/75">Flags resistance increases to warn of early cell degradation.</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <RefreshCw className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Restorative Pulse Charging</p>
                <p className="text-xs text-muted-foreground/75">Suggests custom charge cycles to break down battery dendrite formations.</p>
              </div>
            </div>
          </div>
        )
      },
      {
        title: "Cell Balancing Analytics",
        description: "Monitors delta voltage variance between parallel battery cells to optimize charging speed and health.",
        content: (
          <div className="w-full space-y-3 text-xs text-muted-foreground/80">
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Voltage Delta:</span> Currently under 5mV across all module clusters.
            </div>
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Active Cooling Sync:</span> Activates BMS thermal pumps during fast charging cycles.
            </div>
          </div>
        )
      }
    ]
  },
  charging: {
    title: "Charging Intelligence System",
    subtitle: "Dynamic route planning, automated booking slots, peak demand shifting, and charger speed optimization.",
    categoryName: "Charging Intel",
    stats: [
      { label: "Grid Cost Savings", value: "28% Saved", change: "Arbitrage yield", changeType: "positive" },
      { label: "Optimal Bookings", value: "98% Compliance", change: "Automatic slots", changeType: "positive" },
      { label: "Charging Efficiency", value: "94.2%", change: "Low thermal losses", changeType: "neutral" },
      { label: "Network Stations", value: "1,450 Nodes", change: "Active locations", changeType: "positive" }
    ],
    widgets: [
      {
        title: "Smart Grid Integration",
        description: "Schedules heavy vehicle charging during low-demand night hours, reducing peak utility costs.",
        content: (
          <div className="w-full space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Plug className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Dynamic Grid Shedding</p>
                <p className="text-xs text-muted-foreground/75">Automatically curtails charging rate during local grid overload.</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Settings className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Virtual Power Plant (VPP)</p>
                <p className="text-xs text-muted-foreground/75">Aggregates connected EVs to provide surge capacity back to the grid.</p>
              </div>
            </div>
          </div>
        )
      },
      {
        title: "Intelligent Queue Management",
        description: "AI maps grid congestion levels to direct drivers to the nearest low-utilization high-speed charger.",
        content: (
          <div className="w-full space-y-3 text-xs text-muted-foreground/80">
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Predictive Booking:</span> Pre-books charger slots on highway routes.
            </div>
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Optimal Charging Speed:</span> Adjusts to vehicle thermal limit rules.
            </div>
          </div>
        )
      }
    ]
  },
  recommendations: {
    title: "Smart Recommendations Engine",
    subtitle: "Highly personalized vehicle recommendations and charging station setups tailored to your driving frequency.",
    categoryName: "AI Recs",
    stats: [
      { label: "Profiles Modeled", value: "45,000 Users", change: "Machine learning", changeType: "positive" },
      { label: "Match Success Rate", value: "94.6%", change: "Based on feedback", changeType: "positive" },
      { label: "Inference Latency", value: "< 15ms", change: "Real-time lookup", changeType: "neutral" },
      { label: "Recommendation Models", value: "4 Ensembles", change: "Multi-layered ML", changeType: "neutral" }
    ],
    widgets: [
      {
        title: "Daily Commute Optimization",
        description: "Calculates cost savings, required battery size, and home charger specs based on daily mileage inputs.",
        content: (
          <div className="w-full space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Wand2 className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Daily Range Estimator</p>
                <p className="text-xs text-muted-foreground/75">Suggests optimal battery capacity (kWh) to eliminate range anxiety.</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Settings className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Home Charging Scoping</p>
                <p className="text-xs text-muted-foreground/75">Calculates electrical modifications needed for AC home boxes.</p>
              </div>
            </div>
          </div>
        )
      },
      {
        title: "Corporate Fleet Electrification",
        description: "Recommends custom combinations of light cargo EVs and dual port chargers to maximize operational ROI.",
        content: (
          <div className="w-full space-y-3 text-xs text-muted-foreground/80">
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">ROI Estimator:</span> Projects total cost of ownership savings over 5 years.
            </div>
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Vehicle Matching:</span> Rates vehicles based on payload and cargo limits.
            </div>
          </div>
        )
      }
    ]
  },
  maintenance: {
    title: "Predictive Maintenance Center",
    subtitle: "Edge AI anomaly diagnostic suites that identify structural issues, gear wear, and cell decay before breakdowns occur.",
    categoryName: "Predictive AI",
    stats: [
      { label: "Fault Alerts Issued", value: "1,240 Warns", change: "99.8% True positive", changeType: "positive" },
      { label: "Fleet Downtime", value: "45% Lower", change: "Proactive service", changeType: "positive" },
      { label: "Sensor Channels", value: "128 Streams", change: "Drivetrain telemetry", changeType: "neutral" },
      { label: "Maintenance ROI", value: "3.4x Savings", change: "vs reactive repairs", changeType: "positive" }
    ],
    widgets: [
      {
        title: "Drivetrain Vibrations Diagnostics",
        description: "Scans vibration frequencies from EV motors and gear boxes to identify early shaft imbalances.",
        content: (
          <div className="w-full space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Wrench className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Anomalous Sound Sync</p>
                <p className="text-xs text-muted-foreground/75">Audits engine sound waves to catch stator insulation wear.</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <ShieldAlert className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Critical Insulation Warning</p>
                <p className="text-xs text-muted-foreground/75">Flags early leaks to prevent high-voltage chassis shocks.</p>
              </div>
            </div>
          </div>
        )
      },
      {
        title: "Regenerative Brakes Life Cycles",
        description: "Predicts brake shoe friction coefficient erosion rate using regenerative braking statistics.",
        content: (
          <div className="w-full space-y-3 text-xs text-muted-foreground/80">
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Friction Wear Rate:</span> Decreased by 60% due to regenerative deceleration.
            </div>
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Next Brake Audit:</span> Scheduled in approximately 14,500 miles.
            </div>
          </div>
        )
      }
    ]
  },
  insights: {
    title: "EV Insights & Technology Reports",
    subtitle: "High-quality industry research, technological whitepapers, policy analyses, and daily EV global trends.",
    categoryName: "EV Insights",
    stats: [
      { label: "Research Reports", value: "150+ Papers", change: "Peer-reviewed papers", changeType: "positive" },
      { label: "Active Readers", value: "18,000+ Users", change: "Enterprise clients", changeType: "positive" },
      { label: "Resident Authors", value: "14 Specialists", change: "PhDs & Analysts", changeType: "neutral" },
      { label: "Industry Citations", value: "1,120 Quotes", change: "Reputable insights", changeType: "positive" }
    ],
    widgets: [
      {
        title: "Battery Chemistry Innovations",
        description: "Monitors solid-state battery testing, dry electrode processing, and sodium-ion feasibility studies.",
        content: (
          <div className="w-full space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Lightbulb className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Solid-State Retentions</p>
                <p className="text-xs text-muted-foreground/75">80% capacity retained after 800 charge cycles at 2C rates.</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Sun className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Sodium-Ion Feasibilities</p>
                <p className="text-xs text-muted-foreground/75">Excellent performance at extreme temperatures (-20°C).</p>
              </div>
            </div>
          </div>
        )
      },
      {
        title: "Global Regulatory Watch",
        description: "Comprehensive details on PM E-Drive regulations, state road-tax waivers, and EU carbon quotas.",
        content: (
          <div className="w-full space-y-3 text-xs text-muted-foreground/80">
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">PM E-Drive Subsidy:</span> Active grants mapped for heavy logistics trucks.
            </div>
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Tax Incentives:</span> 100% waiver of road taxes on EVs in multiple states.
            </div>
          </div>
        )
      }
    ]
  },
  "future-lab": {
    title: "Future Mobility Lab",
    subtitle: "Scoping autonomous driving algorithms, bi-directional vehicle-to-grid grid stabilization, and smart city robotic charging.",
    categoryName: "Future Lab",
    stats: [
      { label: "Active Prototypes", value: "8 Systems", change: "Live testing", changeType: "neutral" },
      { label: "Autonomous Miles", value: "2.4M Miles", change: "Simulator & Track", changeType: "positive" },
      { label: "Robo-Charger Uptime", value: "99.5%", change: "Camera guided", changeType: "positive" },
      { label: "V2G Grid Injection", value: "14.5 GWh", change: "Stabilization tests", changeType: "positive" }
    ],
    widgets: [
      {
        title: "Autonomous Shuttle Microgrids",
        description: "Parked autonomous shuttle buses feed battery energy to local grid loops during supply deficit spikes.",
        content: (
          <div className="w-full space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Rocket className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Bi-directional Power Units</p>
                <p className="text-xs text-muted-foreground/75">High-frequency DC injection directly into district substation nodes.</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5">
              <Settings className="w-5 h-5 text-[#FF8C00]" />
              <div>
                <p className="text-sm font-bold text-white">Auto Plug Sync</p>
                <p className="text-xs text-muted-foreground/75">Locks shuttle brakes automatically before beginning V2G power injection.</p>
              </div>
            </div>
          </div>
        )
      },
      {
        title: "Robotic Charging Arms",
        description: "Fully automated parking slots where camera-guided robotic arms plug charging cords into vehicle ports.",
        content: (
          <div className="w-full space-y-3 text-xs text-muted-foreground/80">
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Target Alignment:</span> Computer vision maps exact coordinate limits of socket pins.
            </div>
            <div className="p-2.5 rounded-lg bg-[#FF8C00]/5 border border-[#FF8C00]/10">
              <span className="text-[#FF8C00] font-bold">Auto Disconnection:</span> Unplugs automatically as state-of-charge hits target.
            </div>
          </div>
        )
      }
    ]
  }
};

export function generateStaticParams() {
  return [
    { slug: "assistant" },
    { slug: "analytics" },
    { slug: "battery" },
    { slug: "charging" },
    { slug: "recommendations" },
    { slug: "maintenance" },
    { slug: "insights" },
    { slug: "future-lab" }
  ];
}

interface PageProps {
  params: Promise<{ slug: string }>;
}

export default async function IntelligenceDetailPage({ params }: PageProps) {
  const { slug } = await params;
  
  // Dynamic lookup fallback to "assistant" to ensure 404 is NEVER returned.
  const pageData = (DATA_MAP[slug as string] || DATA_MAP.assistant) as {
    title: string;
    subtitle: string;
    categoryName: string;
    stats: Array<{
      label: string;
      value: string;
      change?: string;
      changeType?: "positive" | "negative" | "neutral";
    }>;
    widgets: Array<{
      title: string;
      description: string;
      content: React.ReactNode;
    }>;
  };

  return (
    <IntelligenceDashboardTemplate
      title={pageData.title}
      subtitle={pageData.subtitle}
      categoryName={pageData.categoryName}
      stats={pageData.stats}
      widgets={pageData.widgets}
    />
  );
}
